package com.cguzowski.paymentcopilot.incident;

public enum IncidentType {
    AUTHORIZATION_DECLINE_RATE_SPIKE,
    AUTHORIZATION_TIMEOUT_SPIKE,
    CAPTURE_FAILURE_SPIKE,
    REFUND_FAILURE_SPIKE,
    SETTLEMENT_DELAY,
    WEBHOOK_DELIVERY_FAILURE,
    RECONCILIATION_MISMATCH
}
